.PHONY:all
all:ExBubbleSort ExQuickSort ExSelectsort
ExSelectsort:Selectsort.cpp
	g++ -0 $@ $^
ExBubbleSort:BubbleSort.cpp
	g++ -0 $@ $^
ExQuickSort:QuickSort.cpp
	g++ -0 $@ $^
.PHONY:clean
clean:
	rm -rf Ex*
